# Test FastAPI endpoints

POST http://localhost:8000/extract_skills
Content-Type: application/json

{
  "text": "John is a Java and Typescript programmer who knows Spring Boot a bit"
}

###

GET http://127.0.0.1:8000/readyz
Accept: application/json

###
