from pydantic import BaseModel, Field


class EmbeddingModelDetails(BaseModel):
  """
  Describes the Sentence Transformers model used to generate an embedding.

  These properties can be populated from the EmbeddingModel table by the
  calling Spring Boot service.
  """

  model_name: str = Field(
    ...,
    min_length=1,
    description="Sentence Transformers model name",
  )

  dimensions: int = Field(
    ...,
    gt=0,
    description="Expected number of dimensions generated by the model",
  )


class GenerateEmbeddingRequest(BaseModel):
  """
  Request for generating an embedding from text.
  """

  text: str = Field(
    ...,
    min_length=1,
    description="Text from which to generate the embedding",
  )

  model: EmbeddingModelDetails


class GenerateEmbeddingResponse(BaseModel):
  """
  Response containing the generated embedding.
  """

  dimensions: int
  embedding: list[float]
