from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, model_validator

class EmbeddingConfigurationVersion(StrEnum):
  """
  Identifies the preprocessing and embedding configuration used to generate
  an embedding.

  Existing configuration versions must not change behaviour after embeddings
  have been generated and stored. A preprocessing change requires a new
  configuration version.
  """

  SBERT_RAW_V1 = "SBERT_RAW_V1"
  SPACY_PREPROCESSING_V1 = "SPACY_PREPROCESSING_V1"
  SPACY_PREPROCESSING_V2 = "SPACY_PREPROCESSING_V2"
  SPACY_PREPROCESSING_V3 = "SPACY_PREPROCESSING_V3"

class EmbeddingModelDetails(BaseModel):
  """
  Identifies the fixed embedding configuration stored in PostgreSQL.

  Embeddings should only be compared when they use the same model name,
  configuration version and dimensions.
  """

  model_config = ConfigDict(frozen=True)

  model_name: str = Field(
    min_length=1,
    description="Name of the Sentence Transformer model.",
  )

  configuration_version: EmbeddingConfigurationVersion = Field(
    min_length=1,
    description=(
      "Version identifying the preprocessing and embedding configuration."
    ),
  )

  dimensions: int = Field(
    gt=0,
    description="Number of dimensions generated by the model.",
  )

class EmbeddingInputType(StrEnum):
  """
  Defines the type of input for generating embeddings.
  The input can either be a document or a query.

  Some embedding models embed query texts differently from the text being searched.

  For example, some models will embed a job description differently from a CV,
  so that the two can be compared more meaningfully.
  """

  DOCUMENT = "DOCUMENT"
  """The input is a document, such as a CV, which will be the target of matching searches."""

  QUERY = "QUERY"
  """The input is a query, such as a job search query."""

class EmbeddingInput(BaseModel):
  """
  Contains one item whose text should be embedded.

  Invalid text is handled as an item-level failure so that the rest of the
  batch can continue.
  """
  id: str = Field(
    min_length=1,
    description=(
      "Caller-supplied identifier used to correlate the result with the "
      "source record. The embedding service does not interpret this value."
    ),
  )

  context: str | None = Field(
    default=None,
    description="Optional context to be used when generating the embedding.",
  )

  text: str | None = Field(
    default=None,
    description="Text from which an embedding should be generated.",
  )

  @model_validator(mode="after")
  def validate_context_or_text_present(self) -> EmbeddingInput:
    """
    Reject inputs with neither context nor text because there would be
    nothing to embed.
    """
    if self.context is None and self.text is None:
      raise ValueError(
        "At least one of context or text must be supplied"
      )

    return self


class EmbeddingsRequest(BaseModel):
  """
  Requests embeddings for multiple inputs using one fixed model
  configuration.
  """

  model: EmbeddingModelDetails

  type: EmbeddingInputType = Field(
    description=(
      "The type of the input text: Query versus documents (i.e., the data "
      "being searched for matches)."
    ),
  )

  inputs: list[EmbeddingInput] = Field(
    min_length=1,
    max_length=500,
  )

  @model_validator(mode="after")
  def validate_unique_ids(self) -> EmbeddingsRequest:
    """
    Reject duplicate IDs because each result must map unambiguously back to
    one database record.
    """
    ids = [item.id for item in self.inputs]

    if len(ids) != len(set(ids)):
      raise ValueError(
        "Input IDs must be unique within the request"
      )

    return self


class EmbeddingErrorCode(StrEnum):
  """
  Stable item-level error codes returned to the batch caller.
  """

  INVALID_TEXT = "INVALID_TEXT"
  PREPROCESSING_FAILED = "PREPROCESSING_FAILED"
  EMBEDDING_FAILED = "EMBEDDING_FAILED"
  INVALID_DIMENSIONS = "INVALID_DIMENSIONS"
  INVALID_EMBEDDING = "INVALID_EMBEDDING"


class EmbeddingError(BaseModel):
  """
  Describes why an individual embedding could not be generated.
  """

  code: EmbeddingErrorCode
  message: str = Field(min_length=1)

class EmbeddingResult(BaseModel):
  """
  Contains the embedding result for one input item.

  The caller-supplied ID is returned unchanged so that the result can be
  correlated with the corresponding input item.

  A successful result contains an embedding and no error. A failed result
  contains an error and no embedding.
  """

  id: str = Field(
    min_length=1,
    description=(
      "Caller-supplied identifier copied unchanged from the corresponding "
      "input item."
    ),
  )

  embedding: list[float] | None = Field(
    default=None,
    description=(
      "Generated embedding vector. Null when embedding generation failed for "
      "this item."
    ),
  )

  error: EmbeddingError | None = Field(
    default=None,
    description=(
      "Details of an item-level failure. Null when the embedding was generated "
      "successfully."
    ),
  )

  @model_validator(mode="after")
  def validate_outcome(self) -> EmbeddingResult:
    """
    Ensure that each result contains exactly one outcome.
    """
    has_embedding = self.embedding is not None
    has_error = self.error is not None

    if has_embedding == has_error:
      raise ValueError(
        "Exactly one of embedding or error must be supplied"
      )

    return self

class EmbeddingsResponse(BaseModel):
  """
  Reports the model used and one result for every requested input.
  """

  model: EmbeddingModelDetails

  requested: int = Field(ge=0)
  succeeded: int = Field(ge=0)
  failed: int = Field(ge=0)

  results: list[EmbeddingResult]

  @model_validator(mode="after")
  def validate_counts(self) -> EmbeddingsResponse:
    """
    Ensure that the summary counts agree with the item-level results.
    """
    if self.requested != len(self.results):
      raise ValueError(
        "Requested count must equal the number of results"
      )

    actual_succeeded = sum(
      result.embedding is not None
      for result in self.results
    )

    actual_failed = sum(
      result.error is not None
      for result in self.results
    )

    if self.succeeded != actual_succeeded:
      raise ValueError(
        "Succeeded count does not match successful results"
      )

    if self.failed != actual_failed:
      raise ValueError(
        "Failed count does not match failed results"
      )

    if self.requested != self.succeeded + self.failed:
      raise ValueError(
        "Requested count must equal succeeded plus failed"
      )

    return self
